name: Setup Custom Domain

on:
  workflow_dispatch:

jobs:
  setup-domain:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Create CNAME file
      run: echo "troyparsons.ca" > public/CNAME
      
    - name: Upload CNAME
      uses: actions/upload-pages-artifact@v3
      with:
        path: public/CNAME
